"""migration

Revision ID: e48c4249de00
Revises: 89a5aa1e2fc4
Create Date: 2025-02-16 17:07:18.170447

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e48c4249de00"
down_revision: Union[str, None] = "89a5aa1e2fc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "answer", sa.Column("is_required", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "test_result",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_result", "created_at")
    op.drop_column("answer", "is_required")
    # ### end Alembic commands ###
