"""migration

Revision ID: 2093880a4f4b
Revises: e48c4249de00
Create Date: 2025-03-02 19:57:38.877918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2093880a4f4b"
down_revision: Union[str, None] = "e48c4249de00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question", sa.Column("s3_file_path", sa.String(), nullable=True)
    )
    op.alter_column(
        "question", "title", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint("question_title_key", "question", type_="unique")
    op.drop_constraint("test_title_key", "test", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("test_title_key", "test", ["title"])
    op.create_unique_constraint("question_title_key", "question", ["title"])
    op.alter_column(
        "question", "title", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("question", "s3_file_path")
    # ### end Alembic commands ###
